name: Deploy to K8s

on:
  push:
    branches:
      - main

jobs:
  build-and-Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Kubernetes
        run: |
          
          kubectl apply -f k8s/deployment.yaml
